//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ComponentPoint.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IComponentPointListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class ComponentPointBaseListener : IComponentPointListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ComponentPointParser.r"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR([NotNull] ComponentPointParser.RContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ComponentPointParser.r"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR([NotNull] ComponentPointParser.RContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ComponentPointParser.position"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPosition([NotNull] ComponentPointParser.PositionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ComponentPointParser.position"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPosition([NotNull] ComponentPointParser.PositionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ComponentPointParser.modifiers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModifiers([NotNull] ComponentPointParser.ModifiersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ComponentPointParser.modifiers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModifiers([NotNull] ComponentPointParser.ModifiersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ComponentPointParser.modifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModifier([NotNull] ComponentPointParser.ModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ComponentPointParser.modifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModifier([NotNull] ComponentPointParser.ModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ComponentPointParser.plusminus"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlusminus([NotNull] ComponentPointParser.PlusminusContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ComponentPointParser.plusminus"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlusminus([NotNull] ComponentPointParser.PlusminusContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ComponentPointParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable([NotNull] ComponentPointParser.VariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ComponentPointParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable([NotNull] ComponentPointParser.VariableContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
