//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ComponentPoint.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ComponentPointParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IComponentPointListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ComponentPointParser.r"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR([NotNull] ComponentPointParser.RContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ComponentPointParser.r"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR([NotNull] ComponentPointParser.RContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ComponentPointParser.position"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPosition([NotNull] ComponentPointParser.PositionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ComponentPointParser.position"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPosition([NotNull] ComponentPointParser.PositionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ComponentPointParser.modifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModifiers([NotNull] ComponentPointParser.ModifiersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ComponentPointParser.modifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModifiers([NotNull] ComponentPointParser.ModifiersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ComponentPointParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModifier([NotNull] ComponentPointParser.ModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ComponentPointParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModifier([NotNull] ComponentPointParser.ModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ComponentPointParser.plusminus"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPlusminus([NotNull] ComponentPointParser.PlusminusContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ComponentPointParser.plusminus"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPlusminus([NotNull] ComponentPointParser.PlusminusContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ComponentPointParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable([NotNull] ComponentPointParser.VariableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ComponentPointParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable([NotNull] ComponentPointParser.VariableContext context);
}
