name: CI
on:
  push: {}
  pull_request:
    types: [ labeled ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Required for nbgv
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    - uses: dotnet/nbgv@v0.4
      id: nbgv
      with:
        path: ./CircuitDiagram
    - run: dotnet restore ./CircuitDiagram/CircuitDiagram.sln
    - run: dotnet test ./CircuitDiagram/CircuitDiagram.sln

    # Windows CLI
    - run: dotnet publish ./CircuitDiagram/CircuitDiagram.CLI/CircuitDiagram.CLI.csproj -c release -r win-x64 -p:PublishSingleFile=true --self-contained true -o ./cli/win-x64
    - run: zip -j ./cli/circuit-diagram-cli.${{ steps.nbgv.outputs.SemVer2 }}.win-x64.zip ./cli/win-x64/* -x **/*.pdb

    # Linux CLI
    - run: dotnet publish ./CircuitDiagram/CircuitDiagram.CLI/CircuitDiagram.CLI.csproj -c release -r linux-x64 -p:PublishSingleFile=true --self-contained true -o ./cli/linux-x64
    - run: tar --exclude **/*.pdb -cJf ../circuit-diagram-cli.${{ steps.nbgv.outputs.SemVer2 }}.linux-x64.tar.gz ./
      working-directory: ./cli/linux-x64

    # OSX CLI
    - run: dotnet publish ./CircuitDiagram/CircuitDiagram.CLI/CircuitDiagram.CLI.csproj -c release -r osx-x64 -p:PublishSingleFile=true --self-contained true -o ./cli/osx-x64
    - run: zip -j ./cli/circuit-diagram-cli.${{ steps.nbgv.outputs.SemVer2 }}.osx-x64.zip ./cli/osx-x64/* -x **/*.pdb

    # Nuget packages
    - run: dotnet pack -c release ./CircuitDiagram/CircuitDiagram.sln -o packages

    - uses: actions/upload-artifact@v3
      with:
        name: circuit-diagram-cli.win-x64
        path: cli/circuit-diagram-cli.${{ steps.nbgv.outputs.SemVer2 }}.win-x64.zip
    - uses: actions/upload-artifact@v3
      with:
        name: circuit-diagram-cli.linux-x64
        path: cli/circuit-diagram-cli.${{ steps.nbgv.outputs.SemVer2 }}.linux-x64.tar.gz
    - uses: actions/upload-artifact@v3
      with:
        name: circuit-diagram-cli.osx-x64
        path: cli/circuit-diagram-cli.${{ steps.nbgv.outputs.SemVer2 }}.osx-x64.zip
    - uses: actions/upload-artifact@v3
      with:
        name: nuget-packages
        path: packages/

  publish-nuget:
    if: github.ref == 'refs/heads/master' || contains(github.event.pull_request.labels.*.name, 'publish')
    runs-on: ubuntu-latest
    needs:
    - build
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: nuget-packages
        path: packages
    - uses: actions/setup-dotnet@v3
    - run: dotnet nuget push ./packages/*.nupkg --skip-duplicate --no-symbols -s https://nuget.pkg.github.com/CircuitDiagram/index.json -k ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
